version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: node:8
    steps:
      - checkout
      - run:
          name: npm i
          command: npm install
      - deploy:
          name: Deploy
          command: |
            if [ "$PREVIEW" == "true" ]
            then
              npm run deploy -- --confirm --preview
            else
              npm run deploy -- --confirm
            fi
